---
openapi: 3.0.1
info:
  title: El Dorado API V1
  version: v1
paths:
  "/api/v1/all_cars/":
    get:
      summary: List all Cars that are created by Admin
      tags:
      - All Cars in the System, Admin Only
      responses:
        '200':
          description: List of all cars found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    image:
                      type: string
                    model:
                      type: string
                    daily_price:
                      type: decimal
                    description:
                      type: text
                    available:
                      type: boolean
                  required:
                  - id
                  - name
                  - image
                  - model
                  - daily_price
                  - description
                  - available
  "/api/v1/cars":
    post:
      summary: Create a New Car
      tags:
      - Create a New Car, Admin Only
      parameters: []
      responses:
        '201':
          description: Car created successfully
        '401':
          description: Unauthorized, only Admin can create a new car
        '422':
          description: Car couldn't be created invalid request or validation failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                image:
                  type: string
                model:
                  type: string
                daily_price:
                  type: decimal
                description:
                  type: text
                available:
                  type: boolean
              required:
              - id
              - name
              - image
              - model
              - daily_price
              - description
              - available
  "/api/v1/cars/{id}":
    put:
      summary: Update a Car
      tags:
      - Update a Car, Admin Only
      parameters:
      - name: id
        in: path
        description: Car ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Car updated successfully
        '401':
          description: You are not authorized to update this car
        '404':
          description: Car not found
        '422':
          description: Car couldn't be updated invalid request or validation failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                image:
                  type: string
                model:
                  type: string
                daily_price:
                  type: decimal
                description:
                  type: text
                available:
                  type: boolean
              required:
              - id
              - name
              - image
              - model
              - daily_price
              - description
              - available
    get:
      summary: List Specific Car
      tags:
      - Get Single Car
      parameters:
      - name: id
        in: path
        description: Car ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Single Car was found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  image:
                    type: string
                  model:
                    type: string
                  daily_price:
                    type: decimal
                  description:
                    type: text
                  available:
                    type: boolean
                required:
                - id
                - name
                - image
                - model
                - daily_price
                - description
                - available
        '404':
          description: Invalid Record not found
  "/api/v1/cars/{id}/availability":
    patch:
      summary: Mark Car as Removed
      tags:
      - Mark Car as Removed/Available, Admin Only
      parameters:
      - name: id
        in: path
        description: Car ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Car updated successfully
        '401':
          description: You are not authorized to update the availability of this car
        '404':
          description: Car not found
        '422':
          description: Car availability couldn't be updated invalid request or validation
            failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                available:
                  type: boolean
              required:
              - available
  "/api/v1/users/{user_id}/reservations":
    get:
      summary: Get user car reservations
      tags:
      - Car Reservations
      parameters:
      - name: user_id
        in: path
        description: Current User ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: User Car reservation found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    pickup_date:
                      type: date
                    return_date:
                      type: date
                    car:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        image:
                          type: string
                        model:
                          type: string
                        daily_price:
                          type: decimal
                        description:
                          type: string
                      required:
                      - id
                      - name
                      - image
                      - model
                      - daily_price
                      - description
                  required:
                  - id
                  - pickup_date
                  - return_date
                  - car
        '401':
          description: You must Login or Register. Car Reservation not found
    post:
      summary: Reserve A Car
      tags:
      - Create Car Reservation
      parameters:
      - name: user_id
        in: path
        description: Current User ID
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Reservation created successfully
        '401':
          description: You need to Sign in before continuing
        '422':
          description: Reservation couldn't be created invalid request or validation
            failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pickup_date:
                  type: date
                return_date:
                  type: date
                car_id:
                  type: integer
              required:
              - pickup_date
              - return_date
              - car_id
  "/api/v1/users/{user_id}/reservations/{id}":
    delete:
      summary: Delete a car reservation
      tags:
      - Remove Car Reservation
      parameters:
      - name: user_id
        in: path
        description: Current User ID
        required: true
        schema:
          type: integer
      - name: id
        in: path
        description: Reservation ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Reservation deleted successfully
        '401':
          description: You need to Sign in before continuing
        '404':
          description: Coudn't find booking with the current id
  "/api/v1/cars/":
    get:
      summary: List all Cars
      tags:
      - List All Available Cars for Rent
      responses:
        '200':
          description: List of available cars found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    image:
                      type: string
                    model:
                      type: string
                    daily_price:
                      type: decimal
                    description:
                      type: text
                    available:
                      type: boolean
                  required:
                  - id
                  - name
                  - image
                  - model
                  - daily_price
                  - description
                  - available
  "/api/v1/login":
    post:
      summary: Sign in User
      tags:
      - Login
      parameters: []
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Logged in failure
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/logout":
    delete:
      summary: Sign out User
      tags:
      - Logout
      parameters:
      - name: Authorization
        in: header
        description: Authorization JWT Token (Check Response Headers in login or register)
        schema:
          type: string
      responses:
        '200':
          description: Logged out successfull
        '401':
          description: Authorization token is invalid
  "/api/v1/register":
    post:
      summary: Register User
      tags:
      - Sign Up
      parameters: []
      responses:
        '200':
          description: User registered successfully
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - name
              - email
              - password
              - password_confirmation
  "/api/v1/users/":
    get:
      summary: Show Current User
      tags:
      - Current User
      responses:
        '200':
          description: Current User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                required:
                - id
                - name
                - email
        '401':
          description: You must Login or Register. Current user not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: eldorado.onrender.com
